- name: Deploy Nginx custom application on K3d
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        src: k8s/deployment.yml

    - name: Deploy Kubernetes Service
      kubernetes.core.k8s:
        state: present
        src: k8s/service.yml
